version: '3'
services:
  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  tailwind:
    build: .
    command: rails tailwindcss:watch
    stdin_open: true
    volumes:
      - .:/app
